Adjust sidetree api to allow nonces and refactor input params
evannetwork/vade-sidetree pull request #8
Opened 2023-02-02 07:05 UTC by S3bb1

This PR adjusts the whole Sidetree api by passing only the public/private keys for the update/recover/deactivate functions and the logic in vade-sidetree then calculates the commitments then.

Also it allows setting the `nonce` property in the public keys when passing them as "next" keys.

Additionally, we now allow setting publicKeys and services directly when creating a did.

2023-02-02 08:40 UTC, Tschuck commented on src/vade_sidetree.rs
> +                    check_commitment = multihash::canonicalize_then_double_hash_then_encode(
can be moved above the if clause, its the same for the update.

2023-02-02 08:40 UTC, Tschuck commented on src/vade_sidetree.rs
> +            _ => return Err(Box::from("Unknown Result".to_string())),
```suggestion
            _ => return Err(Box::from("Unknown Result for did resolve".to_string())),
```

2023-02-02 08:40 UTC, Tschuck commented on src/vade_sidetree.rs
> +            _ => return Err(Box::from("Unknown Result".to_string())),
```suggestion
            _ => return Err(Box::from("Unknown Result while creating did".to_string())),
```

2023-02-02 09:25 UTC, wulfraem requested changes

2023-02-02 09:25 UTC, wulfraem commented on src/vade_sidetree.rs
> +        let result: CreateDidPayload = serde_json::from_str(payload)?;
Could we rename it to something like `payload`? ^^

2023-02-02 10:09 UTC, Tschuck commented on src/vade_sidetree.rs
> +            _ => return Err(Box::from("Unknown Result".to_string())),
```suggestion
            _ => return Err(Box::from("Unknown Result while resolving did".to_string())),
```

2023-02-03 11:59 UTC, wulfraem approved these changes

2023-02-03 12:04 UTC, Tschuck approved these changes

2023-02-03 12:05 UTC, merged